### ISSUE TITLE
Opening screen causes a crash

### ISSUE THREAD

**Issue by cootshk** [mineblock11/Quicksearch#3]
[formatted crash report](https://crashy.net/c90098b7-583d-4a6c-9520-75c1433740ac)
[raw crash report](https://crashy.net/c90098b7-583d-4a6c-9520-75c1433740ac/raw.txt)

**Comment by IMB11** [comment]
I dont guaruntee support with the Quilt Loader. sorry.

**Comment by cootshk** [comment]
Quilt is just fabric with more APIs
